# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171201_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='My location default', max_length=120),
        ),
    ]
